force-app/main/default/objects/Account/fields/shoe_size__c.field-meta.xml
<CustomField>
    <fullName>shoe_size__c</fullName>
    <label>shoe size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>6.5</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>7.5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>8.5</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>9.5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>10.5</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>11.5</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>12.5</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>13.5</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>14.5</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>15.5</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/t_shirt_size__c.field-meta.xml
<CustomField>
    <fullName>t_shirt_size__c</fullName>
    <label>t-shirt size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XXL</fullName>
            </value>
            <value>
                <fullName>XL</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>XS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Unique Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/updatePersonAccountDetailsController.cls
public without sharing class updatePersonAccountDetailsController {
    public Account account { get; set; }

    public updatePersonAccountDetailsController() {
        String encodedId = String.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('id'));
        if (encodedId != null) {
            List<Account> accounts = [SELECT Id, Name, PersonBirthdate, Phone, t_shirt_size__c, shoe_size__c, Unique_Id__c 
                                      FROM Account 
                                      WHERE Unique_Id__c = :encodedId LIMIT 1];
            if (!accounts.isEmpty()) {
                account = accounts[0];
            } else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Account not found.'));
            }
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid or missing account Identifier.'));
        }
    }

    public PageReference save() {
        if (account != null && account.Id != null) {
            try {
                Account accountToUpdate = new Account(
                Id = account.Id,
                PersonBirthdate = account.PersonBirthdate,
                Phone = account.Phone,
                t_shirt_size__c = account.t_shirt_size__c,
                shoe_size__c = account.shoe_size__c,
                Profile_Completed__c = true);
                update accountToUpdate;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Account Information updated successfully.'));
            } catch (DmlException e) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error while updating account, Please correct data and submit again'));
            }
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Account is not properly initialized.'));
        }
        return null;
    }
}